# Generated by Django 2.2 on 2019-02-21 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('year', models.DateField(default=datetime.datetime(2019, 2, 21, 18, 3, 57, 906331))),
            ],
        ),
    ]
